### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by ismaeldcom**
Initial implementation of villain demo. Can be improved, maybe simplified or with a better file organisation, but I think it's ok for a initial version and allow others contributors to participate. And to test the options, because most of them don't update correctly.

Villain options are dynamically loaded from `state.options` and the type inferred, just string, number & boolean for the moment.

Like https://github.com/btzr-io/Villain/issues/81#issuecomment-544813285 said would be interesting to deploy the demo and add a link and preview image to readme, what do you think @btzr-io ?

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #81 

## Preview
image

### CODE REVIEW

**Comment by btzr-io** [comment]
> Like #81 (comment) said would be interesting to deploy the demo

Yeah that would be nice, one the main goal of this project is to have a `web-app` with and `embed` api so you can just use an iframe to integrate on your website instead of the react  component:

```jsx
<iframe src="https://villain-viewer.io/embed?file=path_to_file...." />
```

**Comment by btzr-io** [comment]
Awesome looks great! :rocket: 

One small request: Can you make the theme input a `select` element or perhaps just a button that says toggle dark / light theme ?

Also maybe this can be simplify by defining the props like this:
> Note not all strings should be inputs
```JSX
this.state = {
  theme: { value: 'light', type: 'select', ...more }, // Assigned by state 
  allowFullscreen: { value: false } // Detected by value
}
```

**Comment by ismaeldcom** [comment]
I didn't know about accesslint bot, it detect no label but is present.

I kept both the inferred type version and the new defined one to avoid too much definition boilerplate using an object to only store value, but I remove the old one if you like.

**Comment by btzr-io** [comment]
@ismaeldcom Yeah the bot is not fully compatible with `jsx`, looks good I'll merge now :+1:

**Pull request merged**
