### PR TITLE
fix(render.js): zoom handler event affects animations

### PR DESCRIPTION
**Pull request by Brostafa**
## PR Checklist

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: https://github.com/btzr-io/Villain/issues/66

## What is the current behavior?

The zoom handler function makes the zoom animations choppy and slow.

## What is the new behavior?

The zoom handler function animates smoothly the same way as using mouse wheel

## Other information

It was just a problem with passing `immediately = true` parameter to OpenSeaDragon library.

### CODE REVIEW

**Comment by btzr-io** [comment]
@Brostafa This occurs when you use the wheel mouse (scroll on canvas)
This is the commit that created this issue maybe you could take a look: https://github.com/btzr-io/Villain/commit/a388079a94896b140544f3db19a3e11e573bddf8

**Comment by Brostafa** [comment]
@btzr-io After some profiling I found the issue was with when setting state on every zoom event 
https://github.com/btzr-io/Villain/commit/a388079a94896b140544f3db19a3e11e573bddf8#diff-9d13ed777fc203aef753b28ab30f44efR153 so I have added a debounce to reduce setState invocations and when I re-ran profiling after adding debounce it seems to have become a little bit smoother. Please double-check from your side.

**Comment by btzr-io** [comment]
@Brostafa That's what I think, but it was working fine even when the state was changed on every zoom, try it without this lines on osd.config:  
```
// Animations
  springStiffness: 12,
  springStiffness: 12,
```

**Comment by btzr-io** [comment]
@Brostafa I created a similar solution:
```JS
    let isScrolling = false
    let handleStopScrolling = null

    this.viewer.addHandler('canvas-scroll', event => {
      // Reset scrolling flag
      isScrolling = true
      // Clear our timeout throughout the scroll
      window.clearTimeout(handleStopScrolling)
      // Set a timeout to run after scrolling ends
      handleStopScrolling = setTimeout(() => {
        this.updateZoom()
        isScrolling = false;
      },  750);
    })

    this.viewer.addHandler('zoom', ({zoom}) => {
      // Unable to update zoom on scroll inside this event handler:
      // Bad peformance from multiple context update state calls
      if(!isScrolling) {
        this.updateZoom(zoom)
      }
    })
```

**Comment by btzr-io** [comment]
See: https://github.com/btzr-io/Villain/issues/66#issuecomment-544220050

**Comment by btzr-io** [comment]
@Brostafa I dont see this issue on chrome / brave / electron, only on `firefox`

**Comment by btzr-io** [comment]
@Brostafa I created a patch for firefox (at keast works on my pc) but this issue require more testing and optimizations, here https://github.com/btzr-io/Villain/commit/dd9cf57d17893ed9887447dab96f73a3eb059989 

If you think you can improve something in that commit  or look in to another issue let me know, I'll close this for now, thanks again for all you help :v:

**Comment by Brostafa** [comment]
@btzr-io I couldn't get Firefox on Arch Linux (having dependency hell from doing manual partial updates). Anyway, I booted up Windows to test on Firefox. And I can confirm your commit did improve Firefox performance but didn't improve it for Chrome, that's definitely a step forward either way. I also tested with debounce and that did improve both Firefox and Chrome. If you have time try playing around with debouncing. 

>but not so much for Chrome

May I know why you specifically apply optimization for firefox only?
>      // This can run smooth on chromium based browsers (chrome, brave, electon)
I have seen that comment but does that mean the optimization doesn't play well with chromium based browsers?

https://github.com/btzr-io/Villain/commit/dd9cf57d17893ed9887447dab96f73a3eb059989#diff-9d13ed777fc203aef753b28ab30f44efR206-R215

**Comment by btzr-io** [comment]
@Brostafa I only see this issue on firefox (linux) does it behaves similar on chrome`( windows / linux )?

**Comment by btzr-io** [comment]
My only concern about this new fix is the small delay on the `text update` caused by the `debouncer`, feels kind of odd. Thats why I didnt implemented on all browsers.

I'm still trying to find a way to update the ` current-zoom` text  without a noticeable dalay

**Comment by btzr-io** [comment]
@Brostafa We dont need the `debounce` function when the zoom is not animated ( triggered by buttons or text input). 

Perhaps we should be more consistent whit animations and enable them on button and input triggers ? Feel free to open an issue about this if you have the time ( any other idea / bug )

**Comment by Brostafa** [comment]
@btzr-io Yes, Chrome has little bit of hiccups on Windows. However, when applying your solution (removing it from firefox-only block), Chrome becomes smooth too. Check this video (it doesn't have audio) https://www.loom.com/share/3655f1849f0b4fa29c4ac667cb35579e but again the hiccups are quite small (not that noticable). It may also not be that visible on video as it wasn't recording on a high FPS-rate but if you have Windows laying around you may feel it.

**Comment by btzr-io** [comment]
Nice thanks for testing, would you like to sent a pr with those changes?

**Comment by Brostafa** [comment]
>Nice thanks for testing, would you like to sent a pr with those changes?

I am uncertain because your points here:

>My only concern about this new fix is the small delay on the text update caused by the debouncer, feels kind of odd. Thats why I didnt implemented on all browsers.

>I'm still trying to find a way to update the current-zoom text without a noticeable dalay

are valid and I am not sure of a way to address them. So, I will agree with how you solved the issue for Firefox, if someone complained later we can know how to solve the smooth problem or maybe OpenSeaDragon themselves will make internal optimizations that we don't have to worry about this anymore

**Comment by btzr-io** [comment]
@Brostafa I think for now is ok, maybe I'll also add this fall back for mobile browsers.
Thanks again :v:

**Comment by Brostafa** [comment]
>Perhaps we should be more consistent whit animations and enable them on button and input triggers ? Feel free to open an issue about this if you have the time ( any other idea / bug )
I agree with this. I think too it should animate on button click (not sure if it's worth making PR tho as its changing `immediate: true` param in 2 lines 😄)

**Comment by Brostafa** [comment]
> @Brostafa I think for now is ok, maybe I'll also add this fall back for mobile browsers.

Brilliant!

**Comment by btzr-io** [comment]
For zooming with click now is `doubleClick` https://github.com/btzr-io/Villain/commit/53c7aefd853a870756ea913526f283cfde5fccc6

**Pull request closed without merging**
