### PR TITLE
- Split main css styles into seperate css files

### PR DESCRIPTION
**Pull request by abbasCoder51**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #140 

## What is the current behavior?
Css files style the page

## What is the new behavior?
No Change

### CODE REVIEW

**Comment by btzr-io** [comment]
What is the pr you are working on ?

**Comment by abbasCoder51** [comment]
This is the pull request I'm working on, you can ignore the others

**Comment by btzr-io** [comment]
could you fix the conflicts ?

**Comment by btzr-io** [comment]
@abbasCoder51 I need to update the styles, please fix conflicts and update style file so I can merge this, thanks :v:

**Comment by abbasCoder51** [comment]
There we go

**Pull request merged**
