### PR TITLE
Add pt locale messages

### PR DESCRIPTION
**Pull request by fadc80**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [x] Other - Please describe: Add pt locale messages

## Fixes

Issue Number:

### CODE REVIEW

**Comment by fadc80** [comment]
This is related to #76

**Comment by btzr-io** [comment]
Awesome thanks!
Currently we don't have any framework to handle this but probably this files should exist on its own folder like: `./locales`?

**Comment by btzr-io** [comment]
@fadc80 Could you have the time to look into https://github.com/btzr-io/Villain/issues/80 ?

**Comment by fadc80** [comment]
Should I rebase and squash to a single commit?

**Comment by btzr-io** [comment]
@fadc80 Yes please :+1:

**Pull request merged**
