### PR TITLE
Fix tooltip not hiding on chrome on disabled buttons

### PR DESCRIPTION
**Pull request by giubatt**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes
Fixes tooltip not hiding when mouse hovers out of a disabled button on chromium browsers

Issue Number:
#196 

## What is the current behavior?
Tooltip sometimes is not hidden when mouse leaves a disabled button

## What is the new behavior?
Tooltip is always hidden when mouse leaves a disabled button

### CODE REVIEW

**Comment by btzr-io** [comment]
@giubatt I'm ok with this solution if  doesn't breaks any  styles, but we should look into this: https://github.com/reakit/reakit/issues/471#issuecomment-548241072

**Comment by giubatt** [comment]
I tried what he suggested, changing the events and adding focusable didn't work for it to show on disabled buttons. 
However just adding focusable to the button without changing the events worked, because what it does is instead of setting the button to disabled it only sets aria-disabled to true, so the events work as if it's not disabled (because it's not). 

After changing the css selectors from :disabled to [aria-disabled="true"] all the styles are the same and there's no need for a wrapper. I think this is a better solution. 
The only downside is that you have to style the disabled buttons as the default browser style won't apply, but that is already being done.

As for the menu items, I could add focusable=true if the item is using the component MenuItem, which renders a button (if no "as" prop is passed), so that it works the same as the other buttons. What do you think?

**Comment by giubatt** [comment]
I'll do it on this one

**Comment by giubatt** [comment]
From what I tested the menu items already work fine with tooltips on chromium, because they use the custom button from the project in the content property of each item. So there's no need to change anything. You can merge it :+1:

**Comment by btzr-io** [comment]
Great contribution, thanks :v:

**Pull request merged**
